# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ja9hw6QqxhHw1lkg9B8EYF7MyxAi4qMH
"""

!pip3 install pandas streamlit
import streamlit as st
import os
from io import BytesIO


st.set_page_config(page_title="Chatbot", page_icon="💬")

st.title("💬 RAG Chatbot Demo")
st.write("Ich beantworte deine Fragen")