# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ja9hw6QqxhHw1lkg9B8EYF7MyxAi4qMH
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import os
# 
# # Versuch: Secrets aus Colab (userdata) laden
# try:
#     from google.colab import userdata
#     os.environ["OPENAI_API_KEY"] = userdata.get("OpenAI")
#     os.environ["PINECONE_API_KEY"] = userdata.get("Pinecone")
# except:
#     # Fallback: Streamlit Cloud Secrets
#     os.environ["OPENAI_API_KEY"] = st.secrets.get("OPENAI_API_KEY")
#     os.environ["PINECONE_API_KEY"] = st.secrets.get("PINECONE_API_KEY")
# 
# # Deinen Agenten importieren
# from rag_agent import agent_executor  # Stelle sicher, dass diese Datei im selben Ordner liegt
# 
# # Streamlit UI
# st.set_page_config(page_title="Mein RAG-Assistent", page_icon="🤖")
# 
# st.title("BGV RAG-Assistent 🤖")
# st.markdown("Frage mich etwas zu Themen deiner Wahl!")
# 
# user_input = st.text_input("Deine Frage eingeben:")
# 
# if st.button("Antwort abrufen"):
#     if user_input.strip():
#         with st.spinner("Antwort wird generiert..."):
#             result = agent_executor.invoke({"input": user_input})
#             st.success(result["output"])
#     else:
#         st.warning("Bitte eine Frage eingeben.")