# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ja9hw6QqxhHw1lkg9B8EYF7MyxAi4qMH
"""

import streamlit as st
from ai_agent import get_rag_response



st.set_page_config(page_title="Chatbot", page_icon="💬")

st.title("💬 RAG Chatbot Demo")
st.write("Ich beantworte deine Fragen")

if prompt := st.chat_input("Stelle mir eine Frage..."):
    with st.spinner("Denke nach..."):
        response = get_rag_response(prompt)

    st.write(response)

